version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-type: all
    groups:
      all-gomod:
        patterns:
          - '*'
