version: "3"

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  process:
    desc: Process the modules.
    vars:
      SEED: ./data/seed-goproxy.csv
      PARALLEL: 64
      OFFSET: 0
    cmds:
      - go run . process-modules -parallel={{ .PARALLEL }} -seed-file={{ .SEED }} -offset={{ .OFFSET }} > /tmp/process-modules.log

  fetch-goproxy-seed:
    vars:
      YEAR: 2025
    cmds:
      - |
        go run . list-goproxy-modules \
          -since={{ .YEAR }}-01-01T00:00:00Z \
          -until={{ add .YEAR 1 }}-01-01T00:00:00Z \
          -output-file=./data/goproxy-modules/{{ .YEAR }}-goproxy-modules.csv

  init-goproxy-seed:
    desc: Initialize the seed file with Go modules from the Go proxy.
    sources:
      - ./data/goproxy-modules/*.csv.xz
    generates:
      - ./data/seed-goproxy.csv
    cmds:
      - git lfs install
      - git lfs pull
      - (cd data/goproxy-modules ; unxz -k *.csv.xz)
      - xsv cat rows *.csv > data/seed-goproxy.csv

  neo4j:backup:dump:
    cmds:
      - |
        docker run -it --rm \
          -v ./neo4j/data:/data \
          -v ./neo4j/backups:/backups \
          neo4j:5 \
          neo4j-admin database dump --to-path=/backups neo4j

  neo4j:backup:load:
    preconditions:
      - test -f ./neo4j/backups/neo4j.dump
    cmds:
      - |
        docker run -it --rm \
          -v ./neo4j/data:/data \
          -v ./neo4j/backups:/backups:ro \
          neo4j:5 \
          neo4j-admin database load neo4j \
            --from-path=/backups \
            --overwrite-destination=true
