version: "3"

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  process:
    desc: Process the modules.
    vars:
      SEED: ./data/seed-goproxy.txt
      PARALLEL: 64
      OFFSET: 23241000
    cmds:
      - go run . process-modules -parallel={{ .PARALLEL }} -seed-file={{ .SEED }} -offset={{ .OFFSET }} > /tmp/process-modules.log

  init-goproxy-seed:
    desc: Initialize the seed file with Go modules from the Go proxy.
    sources:
      - ./data/goproxy-modules/*.txt.xz
    generates:
      - ./data/seed-goproxy.txt
    cmds:
      - (cd data/goproxy-modules ; ls *.txt.xz | xargs -I {} tar xJf {})
      - cat data/goproxy-modules/*.txt > data/seed-goproxy.txt

  neo4j:backup:dump:
    cmds:
      - |
        docker run -it --rm \
          -v ./neo4j/data:/data \
          -v ./neo4j/backups:/backups \
          neo4j:5 \
          neo4j-admin database dump --to-path=/backups neo4j

  neo4j:backup:load:
    preconditions:
      - test -f ./neo4j/backups/neo4j.dump
    cmds:
      - |
        docker run -it --rm \
          -v ./neo4j/data:/data \
          -v ./neo4j/backups:/backups:ro \
          neo4j:5 \
          neo4j-admin database load neo4j \
            --from-path=/backups \
            --overwrite-destination=true
