version: "3"

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  process:
    desc: Process the modules.
    vars:
      SEED: ./data/seed-goproxy.txt
      PARALLEL: 64
      OFFSET: 23241000
    cmds:
      - go run . process-modules -parallel={{ .PARALLEL }} -seed-file={{ .SEED }} -offset={{ .OFFSET }} > /tmp/process-modules.log

  init-goproxy-seed:
    desc: Initialize the seed file with Go modules from the Go proxy.
    sources:
      - ./data/goproxy-modules/*.txt.xz
    generates:
      - ./data/seed-goproxy.txt
    cmds:
      - (cd data/goproxy-modules ; ls *.txt.xz | xargs -I {} tar xJf {})
      - cat data/goproxy-modules/*.txt > data/seed-goproxy.txt

  init-seed:
    desc: Initialize the seed file with GitHub repositories.
    generates:
      - ./data/awesome-go.txt
      - ./data/seed.txt
      - ./data/top10.txt
      - ./data/top100.txt
    cmds:
      - bash scripts/init-seed.sh

  convert-seed:
    desc: Convert the seed repositories URLs from the seed to Go module paths.
    sources:
      - ./data/seed.txt
    generates:
      - ./data/seed-modules.txt
    cmds:
      - go run . repositories-to-modules -input-file=./data/seed.txt -output-file=./data/seed-modules.txt
