version: "3"

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  process:
    desc: Process the modules.
    vars:
      SEED: ""
      PARALLEL: 64
      OFFSET: 23241000
    cmds:
      - go run . process-modules -parallel={{ .PARALLEL }} -seed-file={{ .SEED }} -offset={{ .OFFSET }} > /tmp/process-modules.log

  init-seed:
    desc: Initialize the seed file with GitHub repositories.
    generates:
      - ./data/awesome-go.txt
      - ./data/seed.txt
      - ./data/top10.txt
      - ./data/top100.txt
    cmds:
      - bash scripts/init-seed.sh

  convert-seed:
    desc: Convert the seed repositories URLs from the seed to Go module paths.
    sources:
      - ./data/seed.txt
    generates:
      - ./data/seed-modules.txt
    cmds:
      - go run . repositories-to-modules -input-file=./data/seed.txt -output-file=./data/seed-modules.txt

  neo4j:backup:dump:
    cmds:
      - |
        docker run -it --rm \
          -v ./neo4j/data:/data \
          -v ./neo4j/backups:/backups \
          neo4j:5 \
          neo4j-admin database dump --to-path=/backups neo4j

  neo4j:backup:load:
    cmds:
      - |
        docker run -it --rm \
          -v ./neo4j/data:/data \
          -v ./neo4j/backups:/backups \
          neo4j:5 \
          neo4j-admin database load --from-path=/backups neo4j
